[[language]]
name = "rust"
language-id = "rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
language-servers = ["rust-analyzer"]

[[langauge]]
name = "java"
language-id = "java"
file-types = ['java']
roots = ["gradlew", "settings.gradle.kts", "build.gradle"]
langauge-servers = ["jdtls"]

[[language]]
name = "python"
file-types = [
  "py",
  "pyi",
  "py3",
  "pyw",
  "ptl",
  "rpy",
  "cpy",
  "ipy",
  "pyt",
  { glob = ".python_history" },
  { glob = ".pythonstartup" },
  { glob = ".pythonrc" },
  { glob = "SConstruct" },
  { glob = "SConscript" },
]
roots = ["pyproject.toml", "setup.py", "poetry.lock", "pyrightconfig.json"]
language-servers = ["basedpyright"]

[[language]]
name = "go"
language-id = "go"
file-types = ["go"]
roots = ["go.mod", "go.sum"]
language-servers = ["gopls"]

[language-server.gopls]
command = "gopls"
